export type { PageProps, ServicesComponentProps, ProductComponentProps, HomeComponentProps, ContactComponentsProps } from './withStaticPathsAndProps';
export type { GetStaticPaths, GetStaticProps } from 'next';
export { useTheme } from '@mui/material';
export { darkTheme, lightTheme } from '@/theme';
export { default as CalculationSection } from '@/components/ui/calculation-section/CalculationSection';
export { default as DynamicHead } from '@/components/shared/DynamicHead';
export { default as InformationBlock } from '@/components/ui/information-block/InformationBlock';
export { default as InfoCard } from '@/components/ui/info-card/InfoCard';
export { default as Paragraph } from '@/components/ui/typography/Paragraph';
export { default as OurEquipment } from '@/components/ui/equipment/OurEquipment';
export { useEffect, useState } from 'react';
export { default as InfoCardList } from '@/components/ui/info-card/InfoCardList';
export { default as ServiceBlock } from '@/components/ui/service-block/ServiceBlock';
export { default as ListBenefits } from '@/components/ui/list-benefits/ListBenefits';
export { default as FeatureBlock } from '@/components/ui/feature-block/FeatureBlock';
